---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1578665/public_html/hotelnirvana.site
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -a * $DEPLOYPATH



    # - composer update
    # - symbolic link apps to public html
    # - /bin/ln -s /home/u1578665/public_html/patria-maritime-lines.website/storage/app/public /home/u1578665/public_html/patria-maritime-lines.website/public/storage
